# Only session policy runs here. Android owns all physical hardware.
wireplumber.profiles = {
    linux-audio = { inherits = [ policy, mixin.stateless ] }
}
wireplumber.settings = {
    linking.allow-moving-streams = true
    linking.follow-default-target = true
}
